### ISSUE TITLE
404 for link in README

### ISSUE THREAD

**Issue by ligi** [slockit/in3#46]
was very excited to read: "Java-Implementation of a native-wrapper" but then clicked on in and got a 404 :-(

**Comment by simon-jentzsch** [comment]
Yes we have put in the examples already, but the link will work as soon as we will publish the our c-implementation repo. But a 404 is not nice ;-) so I'll remove the link and add a comment.

**Comment by ligi** [comment]
thanks! Hope the repo opens soon. If you need beta-testers let me know - really eager to add in3 support to WallETH ;-)

**Comment by simon-jentzsch** [comment]
yes, I hope so as well. Our current plan would be to release it in Q2 this year, which is very likely to happen. If you want, we can have a chat to see, if you can test even the current version earlier.

**Comment by ligi** [comment]
happy to chat - are you on [matrix]

**Comment by ligi** [comment]
@simon-jentzsch any news on the release? Eagerly awaiting it and it seems it will not be Q2 anymore if you are not in possession of a time machine ,-)

**Comment by dominicletz** [comment]
Yep, also looking for the c-client. What's the ETA?

**Comment by dominicletz** [comment]
@simon-jentzsch was this intentionally closed? The links in the readme still lead to a 404 -- at least for me...
![image](https://user-images.githubusercontent.com/2987674/63317168-5b644080-c344-11e9-80d5-b7b118245856.png)
