### ISSUE TITLE
Incorrect chain name shown on Incube dashboard for Görli

### ISSUE THREAD

**Issue by ltfschoen** [slockit/in3#51]
In this section of the readme https://github.com/slockit/in3#g%C3%B6rli, if I click the link to go to the Incubed dashboard for Goerli https://in3.slock.it/?n=goerli, I expected the title at the top to be Görli, however it displays the Tobalaba title and information about that chain instead

**Comment by simon-jentzsch** [comment]
yes I could reproduce it and fix it. The Problem was a bug when decoding the url of the nodelist of goerli. Since the url was exactly 32 byte long he tried to read one more slot, which did not exist.

So gthe current develop-branch of the C-Client should be working.
