### ISSUE TITLE
Link to API Doc not working

### ISSUE THREAD

**Issue by christianbrb** [slockit/in3#53]
Dear Slockit-Team, 
I have tried to read the [API Doc](https://github.com/slockit/in3/blob/master/docs/api.md#type-api), but the link is giving me a 404.
Kind Regards
@christianbrb

**Comment by simon-jentzsch** [comment]
thanks, can you remember where the link was included?

At the moment we moved all the documentation to readthedocs : https://in3.readthedocs.io/en/develop/

Here you will also find the API Doc included. But if there are some old link, we should fix them ;-)

**Comment by christianbrb** [comment]
@simon-jentzsch Thanks :-)

Yes, it's [here](https://github.com/slockit/in3/blame/master/README.md#L228)
